"""
Assemble a self-contained directory for `reflex deploy`.

    python -m scripts.prepare_deploy
    cd build/deploy && reflex init && reflex deploy --region syd

Reflex Cloud zips the *working directory* of the deploy command, and that
directory has to be the one holding rxconfig.py -- which here is `app/`.
That breaks this project three ways, all of them found by exporting the
package locally and reading the file list rather than by deploying and
watching it fail:

1. `src/` and `data/` live in the repo root, one level above `app/`, so
   they are simply not in the archive. `rxconfig.py` puts the repo root on
   sys.path, which works on a development machine because the files are
   there, and cannot work in the cloud because they were never uploaded.
2. `app/requirements.txt` pins reflex and nothing else. The real
   dependency list is at the repo root, and without it the deployed app
   has no psycopg2, no spaCy and no sentence-transformers.
3. **`app/uploaded_files/` is included.** Reflex's packager does not read
   .gitignore -- that only governs the advice in its size-limit error --
   so resumes uploaded through the UI, with real names, phone numbers and
   addresses, end up in the upload. This script exists mainly to make that
   impossible: the staging tree is built by copying an explicit allowlist,
   so a new directory in `app/` is excluded by default rather than
   included by default.

The layout below is also what makes DATA_ROOT resolve correctly without
an environment variable: config.py takes `parents[2]` of
`src/matching/config.py`, which lands on the staging root, exactly as it
lands on the repo root in development.
"""
from __future__ import annotations

import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
STAGING = REPO_ROOT / "build" / "deploy"

# Everything that ships, named one by one. Anything not listed is absent
# from the deployment, which is the safe direction for a tree that also
# holds uploaded resumes.
DIRECTORIES = [
    ("app/resume_matcher", "resume_matcher"),
    ("src", "src"),
    ("data/samples", "data/samples"),
]
FILES = [
    ("requirements.txt", "requirements.txt"),
    ("data/processed/bm25_corpus_stats.json", "data/processed/bm25_corpus_stats.json"),
    # Not data/taxonomy/: the ESCO relations CSV is 26.7MB and Reflex
    # Cloud's extractor rejects any archive entry over 25MiB, which is what
    # failed the first deployment. The derived adjacency map is 3.9MB and
    # gives the same suggestions -- see scripts/build_adjacency_cache.py.
    ("data/processed/esco_adjacency.json.gz", "data/processed/esco_adjacency.json.gz"),
]

# rxconfig.py is rewritten rather than copied. The committed one adds the
# *parent* of its own directory to sys.path, which is right when it sits
# in app/ and wrong once it sits at the staging root next to src/.
RXCONFIG = '''"""Generated by scripts/prepare_deploy.py -- do not edit here."""
import sys
from pathlib import Path

import reflex as rx

# In the staging tree src/ is a sibling of this file, not an uncle.
PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

config = rx.Config(
    app_name="resume_matcher",
)
'''

IGNORE = shutil.ignore_patterns(
    "__pycache__", "*.pyc", "*.pyo", ".DS_Store", ".web", ".states",
    "uploaded_files", "*.log",
)


def build() -> Path:
    if STAGING.exists():
        shutil.rmtree(STAGING)
    STAGING.mkdir(parents=True)

    for source, target in DIRECTORIES:
        src_path = REPO_ROOT / source
        if not src_path.exists():
            print(f"  missing, skipped: {source}")
            continue
        shutil.copytree(src_path, STAGING / target, ignore=IGNORE)
        print(f"  {source}/ -> {target}/")

    for source, target in FILES:
        src_path = REPO_ROOT / source
        if not src_path.exists():
            print(f"  missing, skipped: {source}")
            continue
        destination = STAGING / target
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_path, destination)
        print(f"  {source} -> {target}")

    (STAGING / "rxconfig.py").write_text(RXCONFIG)
    print("  rxconfig.py (regenerated for the staging layout)")
    return STAGING


def verify(staging: Path) -> bool:
    """Refuse to hand over a tree that leaks resumes or misses the engine."""
    ok = True

    leaked = [p for p in staging.rglob("*")
              if p.is_file() and ("uploaded_files" in p.parts or p.suffix.lower() == ".pdf"
                                  and "samples" not in p.parts)]
    if leaked:
        ok = False
        print("\n  REFUSING: uploaded resumes found in the staging tree:")
        for path in leaked[:10]:
            print(f"    {path.relative_to(staging)}")

    required = [
        "rxconfig.py", "requirements.txt", "resume_matcher/service.py",
        "src/matching/config.py", "src/ingestion/pipeline.py",
        "data/processed/bm25_corpus_stats.json",
        "data/processed/esco_adjacency.json.gz",
    ]

    # Reflex Cloud's extractor rejects the whole archive on one oversized
    # entry, and it does so after the upload. Cheaper to catch here.
    oversized = [p for p in staging.rglob("*")
                 if p.is_file() and p.stat().st_size > 25 * 1024 * 1024]
    for path in oversized:
        ok = False
        print(f"  REFUSING: {path.relative_to(staging)} is "
              f"{path.stat().st_size / 1_000_000:.1f}MB, over the 25MiB per-file limit")
    for relative in required:
        if not (staging / relative).exists():
            ok = False
            print(f"  REFUSING: missing {relative}")

    requirements = (staging / "requirements.txt").read_text()
    if "reflex" not in requirements or "psycopg2" not in requirements:
        ok = False
        print("  REFUSING: requirements.txt is not the full dependency list")

    total = sum(p.stat().st_size for p in staging.rglob("*") if p.is_file())
    print(f"\n  staged {total / 1_000_000:.1f}MB")
    if total > 100_000_000:
        ok = False
        print("  REFUSING: over the 100MB deployment payload limit")
    return ok


def main() -> None:
    print(f"staging into {STAGING.relative_to(REPO_ROOT)}")
    staging = build()
    if not verify(staging):
        raise SystemExit("staging tree rejected -- see above")
    print("\nok. Next:")
    print(f"  cd {STAGING.relative_to(REPO_ROOT)}")
    print("  reflex init && reflex deploy --region syd --env DATABASE_URL=...")


if __name__ == "__main__":
    main()
